[basic]
debug = false
secret_key = 'your django secret key'

## database 设置
# 本地debug
[debug_db]
name = 'your db name'
host = 'server host'
port = 3306
user = 'db account'
pwd = 'db password'

# 生产上线
[release_db]
name = 'your db name'
host = 'server host'
port = 3306
user = 'db account'
pwd = 'db password'
