# Generated by Django 6.0.1 on 2026-02-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=10)),
                ('cover_description', models.TextField(blank=True, default='', null=True)),
                ('detail_description', models.TextField(blank=True, default='', null=True)),
                ('location', models.CharField(default='', max_length=100)),
                ('camera', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('cover', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('url', models.TextField(default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gallery',
                'ordering': ['-title'],
            },
        ),
    ]
