# Generated by Django 6.0.1 on 2026-03-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'public'), (2, 'private'), (3, 'trash')], default=1),
        ),
    ]
