# Generated by Django 6.0.1 on 2026-02-02 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BGImg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_urls', models.TextField()),
                ('show_number', models.IntegerField(default=3)),
                ('total_number', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Explorer',
            fields=[
                ('id', models.CharField(blank=True, default='', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, default='Not lazy, But write nothing.', max_length=200, null=True)),
                ('region', models.CharField(blank=True, default='Earth', max_length=100, null=True)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_photo', models.CharField(default='', max_length=200)),
                ('level', models.IntegerField(choices=[(0, 'admin'), (1, 'normal'), (2, 'guest')], default=1, editable=False)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Explorer',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('profile_icon', models.CharField(default=': )', max_length=8)),
                ('color', models.CharField(default='#000000', max_length=10)),
                ('nickname', models.CharField(max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('level', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Message',
                'ordering': ['-level', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('signature', models.TextField(blank=True)),
                ('people_cnt', models.BigIntegerField()),
                ('duration_time', models.DurationField()),
            ],
        ),
    ]
