# Generated by Django 6.0.1 on 2026-02-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgimg',
            name='cat_img_urls',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
