# Generated by Django 6.0.1 on 2026-02-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_bgimg_cat_img_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgimg',
            name='cat_says',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bgimg',
            name='cat_img_urls',
            field=models.TextField(default=''),
        ),
    ]
