# Generated by Django 6.0.1 on 2026-03-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_bgimg_cat_says_alter_bgimg_cat_img_urls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgimg',
            options={'ordering': ['-order']},
        ),
        migrations.AddField(
            model_name='bgimg',
            name='backup_img_urls',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bgimg',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='bgimg',
            table='bgimg',
        ),
    ]
