"""
Django settings for mysite project.
Generated by 'django-admin startproject' using Django 4.2.26.
"""
from django.core.management.utils import get_random_secret_key
from pathlib import Path
import os
import tomli


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CDN_URL = "http://cdn.weinnz.com"
LOG_FNAME = ""
BLOG_ITEM_NUM_PER_PAGE = 25
COLOR_LIST = ["#6E2717", "#146923", "#182667", "#711878", "#14635F", "#797E17"]
EMOJI_LIST = [": )", ": (", ": >", ": <", ": b", ": D", ": P", "x )", "x (", "x >", "x <", "x b", "x D", "x P"]
CAT_IMG = ['https://cdn.weinnz.com/static/cat-1.png', 'https://cdn.weinnz.com/static/cat-2.png', 'https://cdn.weinnz.com/static/cat-3.png', 'https://cdn.weinnz.com/static/cat-4.png']
CAT_SAY = ['Owner is out.', 'Owner is not at home.', 'Owner is away.', 'Master is out.', 'Master is not at home.', 'Master is away.']

# Config
with open(BASE_DIR/'secrets.toml', 'rb') as file:
    cfg = tomli.load(file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = cfg['basic'].get('secret_key', get_random_secret_key)
DEBUG = cfg['basic'].get('debug', False)
CSRF_TRUSTED_ORIGINS = ['https://*.weinnz.com', 'https://weinnz.com']

#ALLOWED_HOSTS = ['localhost','127.0.0.1']
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_extensions",
    'django_apscheduler',
    'web',
    'blog',
    'gallery',
    'recipe',
    'works',
    'notes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
DB_CFG = cfg['debug_db'] if DEBUG else cfg['release_db']
DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.mysql', # 使用MySQL数据库
       'NAME': DB_CFG['name'], # 数据库名称
       'HOST': DB_CFG['host'], # 数据库地址
       'PORT': DB_CFG['port'], # 数据库端口
       'USER': DB_CFG['user'], # 数据库用户名
       'PASSWORD': DB_CFG['pwd'] # 数据库密码
   }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# log config
from filelock import FileLock
import logging
from logging.handlers import TimedRotatingFileHandler

class CustomTimedRotatingFileHandler(TimedRotatingFileHandler):
    def doRollover(self):
        with FileLock(self.baseFilename + ".lock"):
            super().doRollover()
#LOGGING_DIR 日志文件存放目录
LOGGING_DIR = "logs" # 日志存放路径
if not os.path.exists(LOGGING_DIR):
    os.mkdir(LOGGING_DIR)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {filename} {funcName} {lineno} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{funcName} {asctime} {message}',
            'datefmt': '%Y-%m-%d-%H-%M-%S',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'mysite.settings.CustomTimedRotatingFileHandler',
            'filename': 'logs/views.log',
            'when': 'M',
            'interval': 30,
            'backupCount': 7,
            'formatter': 'simple',
            'encoding': 'utf-8'
        },
    },
    'loggers': {
        'request': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': 'False',
        },
    },
}

