# Generated by Django 6.0.1 on 2026-02-02 13:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('name_en', models.CharField(blank=True, default='', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Category',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Column',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('name_en', models.CharField(blank=True, default='', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Tag',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('abstract', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('status', models.IntegerField(choices=[(0, 'draft'), (1, 'published_public'), (2, 'published_private'), (3, 'trashed')], default=1)),
                ('views_count', models.IntegerField(default=0, editable=False)),
                ('likes_count', models.IntegerField(default=0, editable=False)),
                ('comments_count', models.IntegerField(default=0, editable=False)),
                ('words_count', models.CharField(default=0, editable=False, max_length=16)),
                ('read_time', models.CharField(default=0, editable=False, max_length=16)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.explorer')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.category')),
                ('columns', models.ManyToManyField(blank=True, related_name='blogs', to='blog.column')),
                ('tags', models.ManyToManyField(blank=True, related_name='blogs', to='blog.tag')),
            ],
            options={
                'db_table': 'blog',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('profile_icon', models.CharField(default=': )', max_length=8)),
                ('color', models.CharField(default='#000000', max_length=10)),
                ('nickname', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=200)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog')),
            ],
            options={
                'db_table': 'blog_comment',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='BlogLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.blog')),
            ],
            options={
                'db_table': 'blog_like',
                'ordering': ['create_time'],
            },
        ),
    ]
