# Generated by Django 6.0.1 on 2026-02-07 06:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0003_bgimg_cat_says_alter_bgimg_cat_img_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_Notes',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('cover', models.CharField(max_length=200)),
                ('abstract', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('location', models.CharField(max_length=200)),
                ('views_count', models.IntegerField(default=0, editable=False)),
                ('likes_count', models.IntegerField(default=0, editable=False)),
                ('comments_count', models.IntegerField(default=0, editable=False)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'travelnote',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='Reading_Notes',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('book', models.CharField(max_length=200)),
                ('cover', models.CharField(max_length=200)),
                ('abstract', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('views_count', models.IntegerField(default=0, editable=False)),
                ('likes_count', models.IntegerField(default=0, editable=False)),
                ('comments_count', models.IntegerField(default=0, editable=False)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.explorer')),
            ],
            options={
                'db_table': 'readingnote',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='ReadingNoteComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('profile_icon', models.CharField(default=': )', max_length=8)),
                ('color', models.CharField(default='#000000', max_length=10)),
                ('nickname', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=200)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notes.reading_notes')),
            ],
            options={
                'db_table': 'reading_note_comment',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='ReadingNoteLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='notes.reading_notes')),
            ],
            options={
                'db_table': 'reading_note_like',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='TravelNoteComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('profile_icon', models.CharField(default=': )', max_length=8)),
                ('color', models.CharField(default='#000000', max_length=10)),
                ('nickname', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=200)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notes.travel_notes')),
            ],
            options={
                'db_table': 'travel_note_comment',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='TravelNoteLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='notes.travel_notes')),
            ],
            options={
                'db_table': 'travel_note_like',
                'ordering': ['create_time'],
            },
        ),
    ]
