# Generated by Django 6.0.1 on 2026-02-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading_notes',
            name='read_time',
            field=models.CharField(default='Feb. 7,2016', max_length=100),
        ),
        migrations.AddField(
            model_name='travel_notes',
            name='travel_time',
            field=models.CharField(default='Feb. 7,2016', max_length=100),
        ),
    ]
