# Generated by Django 6.0.1 on 2026-02-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_reading_notes_read_time_travel_notes_travel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading_notes',
            name='read_time',
        ),
        migrations.RemoveField(
            model_name='travel_notes',
            name='travel_time',
        ),
    ]
