# Generated by Django 6.0.1 on 2026-02-07 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_reading_notes_read_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading_notes',
            options={'ordering': ['-read_time']},
        ),
        migrations.AlterModelOptions(
            name='travel_notes',
            options={'ordering': ['-travel_time']},
        ),
        migrations.AddField(
            model_name='reading_notes',
            name='read_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel_notes',
            name='travel_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
