# Generated by Django 6.0.1 on 2026-02-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_reading_notes_options_and_more'),
        ('web', '0003_bgimg_cat_says_alter_bgimg_cat_img_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_notes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.explorer'),
        ),
    ]
