# Generated by Django 4.2.28 on 2026-02-14 04:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_bgimg_cat_says_alter_bgimg_cat_img_urls'),
        ('notes', '0005_travel_notes_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Life_Notes',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('cover', models.CharField(max_length=200)),
                ('abstract', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('theme', models.CharField(max_length=200)),
                ('views_count', models.IntegerField(default=0, editable=False)),
                ('likes_count', models.IntegerField(default=0, editable=False)),
                ('comments_count', models.IntegerField(default=0, editable=False)),
                ('record_time', models.DateTimeField()),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.explorer')),
            ],
            options={
                'db_table': 'lifenote',
                'ordering': ['-record_time'],
            },
        ),
        migrations.CreateModel(
            name='LifeNoteLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='notes.life_notes')),
            ],
            options={
                'db_table': 'life_note_like',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='LifeNoteComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('profile_icon', models.CharField(default=': )', max_length=8)),
                ('color', models.CharField(default='#000000', max_length=10)),
                ('nickname', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=200)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notes.life_notes')),
            ],
            options={
                'db_table': 'life_note_comment',
                'ordering': ['create_time'],
            },
        ),
    ]
